### PR TITLE
Allowing a data format for the cell to help handle dates, percentages…

### PR DESCRIPTION
**Pull request by pjmeadmtu**
…, etc.

### CODE REVIEW

**Comment by kellyselden** [comment]
What is this C# nonsense... 😉

**Comment by kellyselden** [comment]
Can you publish your NPOI code so I can see how you are consuming this? Also, can you think of a way to get test coverage for this? Maybe calling the constructor in a test a verify the property is what you expect.

**Comment by kellyselden** [comment]
Tests look good. Can you rebase on master because I added CI that runs the tests. Also, I wouldn't mind seeing your ExcelAbstraction.NPOI branch on how you're using this.

**Comment by pjmeadmtu** [comment]
https://github.com/pjmeadmtu/ExcelAbstraction.NPOI/blob/cell-data-format/ExcelAbstraction.NPOI/ExcelService.cs - Lines 348 - 355

**Comment by pjmeadmtu** [comment]
You know that Excel is :1st_place_medal: around here.

**Comment by kellyselden** [comment]
I'm on a mac at work, so I'll have to wait to upload to NuGet.

**Comment by pjmeadmtu** [comment]
Thanks for jumping on that.

**Pull request merged**
